[package]
org = "wso2healthcare"
name = "testCerner_0.1.0"
version = "0.1.0"
export = ["testCerner_0.1.0"]
distribution = "2201.1.2"
authors = ["WSO2 Healthcare"]
keywords = ["Healthcare","FHIR","Cerner"]

[build-options]
observabilityIncluded = true
