base="https://fhir-ehr-code.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d"
tokenUrl="https://authorization.cerner.com/tenants/ec2458f2-1e24-41c8-b71b-0e701af7583d/protocols/oauth2/profiles/smart-v1/token"
clientId="977f278f-eb3f-411e-b2ff-16c554501d69"
clientSecret="AW0nwz9LqNrb_pTzxUHsbqey1f0bzRv_"
scopes=["system/Patient.read","system/Patient.write","system/Observation.write","system/Observation.read","system/Encounter.read","system/Encounter.write"]
domain="localhost"